name: weather_forecast_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_weather_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  hive: ^2.2.3
  http: ^0.13.6
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
